### ISSUE TITLE
How about a method that will add it to the dictionary if it doesnt exist?

### ISSUE THREAD

**Issue by JohnBergman** [Vettvangur/Vettvangur.DictionaryHelper#1]
Dictionary.Get("keyname","default Value" [,"optional language"])?

**Comment by gardarthorsteins** [comment]
Hi John, Yes that should not be a problem to implement.  Will try to finish it today.

**Comment by gardarthorsteins** [comment]
There are 2 new optional parameters available now.

Default value: If dictionary item is not found and has empty value then default value will be returned.
Create:  If key does not exist it will be created. Requires default value
