### ISSUE TITLE
[Bug] Extensions.DictionaryValue Throws System.InvalidOperationException

### ISSUE THREAD

**Issue by danielmpetrov** [Vettvangur/Vettvangur.DictionaryHelper#4]
Hi and thanks for the library.

I am working on an Umbraco v8.5.3 solution that has multiple web projects. Using the extension method on projects that are not the Umbraco frontend throws an exception on line 24 in `Extensions.DictionaryValue`

https://github.com/Vettvangur/Vettvangur.DictionaryHelper/blob/1ee6978e80bc1b86bd1627b9ef2ab6c438e298e4/Extensions.cs#L24

with the following message:

`System.InvalidOperationException: 'Cannot return the IPublishedContent because the UmbracoHelper was not constructed with an IPublishedContent.'`

The source of the exception is in the `UmbracoHelper.AssignedContentItem` getter:

https://github.com/umbraco/Umbraco-CMS/blob/2f10051ee9780cd22d4d1313e5e7c6b0bc4661b1/src/Umbraco.Web/UmbracoHelper.cs#L128

In `Extensions.DictionaryValue` you are handling a case where `null` is returned, but UmbracoHelper is throwing an exception instead. Return of `null` is not possible.

**Comment by gardarthorsteins** [comment]
Hi Daniel, 

Its better late then never right ? :)

So your problem is that you are trying to use the helper somewhere where you don't have the context to use the UmbracoHelper.

In those cases you can use the DictionaryHelper Service like so:

Service.GetValueByKeyAndCulture("key", "en-GB")

**Comment by danielmpetrov** [comment]
Thanks for the reply anyway, indeed better than never! Maybe it helps someone else.

I've opened this issue what seems like a lifetime ago, and I no longer work with Umbraco, so I'll have to take your word on this. 👍
